name: researcher

description: Example demonstrating how to use the library merging_builder.

version: 0.0.1

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  build: ^2.4.1
  researcher_builder:
    path: ../researcher_builder

dev_dependencies:
  build_runner: ^2.4.9
  build_test: ^2.2.2
  lints: ^3.0.0
  source_gen: ^1.5.0
  test: ^1.25.4

dependency_overrides: null

# source_gen:
#   git:
#     url: git@github.com:dart-lang/source_gen.git
#     ref: master
#     path: source_gen
