// GENERATED CODE. DO NOT MODIFY. Generated by AddNamesGenerator.

// Header specified in build.yaml.
final name0 = ['Sarah', 'Martens'];
final name1 = ['Thomas', 'Mayor'];
final name2 = ['Jake', 'Smith'];

final List<List<String>> names = [
  ['Sarah', 'Martens'],
  ['Thomas', 'Mayor'],
  ['Jake', 'Smith'],
];

// Footer specified in build.yaml.
