include: package:lints/recommended.yaml
analyzer:
  #exclude: [build/**]
  #strong-mode:
    #implicit-casts: false

linter:
  rules:
    - camel_case_types
    - avoid_final_parameters: true
    - parameter_assignments: true