name: researcher_builder

description: Example demonstrating how to use the library merging_builder.

version: 0.0.1

publish_to: none

environment:
  sdk: '^3.0.3'

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  build_config: ^1.1.1
  merging_builder: ^0.2.7
  quote_buffer: ^0.2.6
  researcher:
    path: ../researcher
  source_gen: ^1.5.0

dev_dependencies:
  lints: ^3.0.0

dependency_overrides: null

# source_gen:
#   git:
#     url: git@github.com:dart-lang/source_gen.git
#     ref: master
#     path: source_gen
