name: researcher_builder

description: Example demonstrating how to use the library merging_builder.

version: 0.0.1

publish_to: none

environment:
  sdk: '^3.9.0'

dependencies:
  analyzer: ^8.3.0
  build: ^4.0.1
  build_config: ^1.2.0
  merging_builder:
    # git:
    #   url: git@github.com:simphotonics/merging_builder.git
    #   ref: main
    path: ../../merging_builder
  quote_buffer: ^0.2.7
  researcher:
    path: ../researcher
  source_gen: ^4.0.2

dev_dependencies:
  lints: ^6.0.0

# dependency_overrides:
