name: researcher_builder

description: Example demonstrating how to use the library merging_builder.

version: 0.0.1

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^5.4.0
  build: ^2.3.1
  build_config: ^1.1.1
  merging_builder: ^0.2.4
  quote_buffer: ^0.2.3
  researcher:
    path: ../researcher
  source_gen: ^1.2.7

dev_dependencies:
  lints: ^2.0.1

dependency_overrides: null

# source_gen:
#   git:
#     url: git@github.com:dart-lang/source_gen.git
#     ref: master
#     path: source_gen
